FROM node:16 as builder

ARG REACT_APP_AUTH_BACKEND_URL

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install -g pm2

COPY . .

ENV REACT_APP_AUTH_BACKEND_URL=$REACT_APP_AUTH_BACKEND_URL

RUN npm run build

CMD ["pm2", "serve", "build", "--port=2000", "--spa", "--no-daemon"]